{% set git_user = "buck10" %}
{% set git_name = "python-seo-analyzer" %}
{% set version = "4.0.7.a" %}
{% set name = "seoanalyzer" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/{{ git_user }}/{{ git_name }}.git
  git_ver: {{ version }}

requirements:
  host:
    - python
    - beautifulsoup4
    - lxml
    - requests
    - jinja2
    - urllib3
    - certifi
  run:
    - python
    - beautifulsoup4
    - lxml
    - urllib3

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/{{ git_user }}/{{ git_name }}
  summary: SEO Analyzer
